# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.la/la/property_status_single.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.nic.la", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.nic.la/la/property_status_single.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.nic.la")
    Whois::Parser.parser_for(part)
  end

  it "matches property_status_single.expected" do
    expect(subject.status).to eq(["OK"])
  end
end
