# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.registry.qa/qa/property_nameservers_without_ips.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.registry.qa", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.registry.qa/qa/property_nameservers_without_ips.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.registry.qa")
    Whois::Parser.parser_for(part)
  end

  it "matches property_nameservers_without_ips.expected" do
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(3)
    expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[0].name).to eq("ns1.qatarbank.com")
    expect(subject.nameservers[0].ipv4).to eq(nil)
    expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[1].name).to eq("ns2.qatarbank.com")
    expect(subject.nameservers[1].ipv4).to eq(nil)
    expect(subject.nameservers[2]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[2].name).to eq("ns3.qatarbank.com")
    expect(subject.nameservers[2].ipv4).to eq(nil)
  end
end
