# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.jprs.jp/jp/status_reserved.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.jprs.jp", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.jprs.jp/jp/status_reserved.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.jprs.jp")
    Whois::Parser.parser_for(part)
  end

  it "matches status_reserved.expected" do
    expect(subject.status).to eq(:reserved)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to eq(nil)
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2001-02-21 00:00:00 JST"))
    expect(subject.expires_on).to eq(nil)
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers).to eq([])
  end
end
