# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.register.bg/bg/property_nameservers_with_ip.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.register.bg", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.register.bg/bg/property_nameservers_with_ip.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.register.bg")
    Whois::Parser.parser_for(part)
  end

  it "matches property_nameservers_with_ip.expected" do
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(2)
    expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[0].name).to eq("chicken.orbitel.bg")
    expect(subject.nameservers[0].ipv4).to eq("195.24.32.5")
    expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[1].name).to eq("ns.orbitel.bg")
    expect(subject.nameservers[1].ipv4).to eq("195.24.32.2")
  end
end
