# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.rnids.rs/rs/case_token_whois_privacy.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.rnids.rs", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.rnids.rs/rs/case_token_whois_privacy.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.rnids.rs")
    Whois::Parser.parser_for(part)
  end

  it "matches case_token_whois_privacy.expected" do
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts).to eq([])
    expect(subject.admin_contacts).to be_a(Array)
    expect(subject.admin_contacts).to eq([])
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts).to eq([])
  end
end
