# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.jprs.jp/ne.jp/property_created_on_missing.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.jprs.jp", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.jprs.jp/ne.jp/property_created_on_missing.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.jprs.jp")
    Whois::Parser.parser_for(part)
  end

  it "matches property_created_on_missing.expected" do
    expect(subject.created_on).to eq(nil)
  end
end
