# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.tonic.to/to/response_incomplete.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.tonic.to", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.tonic.to/to/response_incomplete.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.tonic.to")
    Whois::Parser.parser_for(part)
  end

  it "matches response_incomplete.expected" do
    expect(subject.status).to eq(:incomplete)
    expect(subject.response_incomplete?).to eq(true)
  end
end
