# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.iis.se/se/property_status_inactive.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.iis.se", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.iis.se/se/property_status_inactive.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.iis.se")
    Whois::Parser.parser_for(part)
  end

  it "matches property_status_inactive.expected" do
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to eq(DateTime.parse("2000-11-01"))
    expect(subject.updated_on).to eq(nil)
    expect(subject.expires_on).to eq(DateTime.parse("2006-04-18"))
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts).to eq([])
    expect(subject.admin_contacts).to be_a(Array)
    expect(subject.admin_contacts).to eq([])
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts).to eq([])
    expect(subject.registrar).to be_a(Whois::Parser::Registrar)
    expect(subject.registrar.name).to eq("CoreRegistry")
  end
end
