# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.cnnic.cn/cn/property_status_reserved_list.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.cnnic.cn", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.cnnic.cn/cn/property_status_reserved_list.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.cnnic.cn")
    Whois::Parser.parser_for(part)
  end

  it "matches property_status_reserved_list.expected" do
    expect(subject.status).to eq([])
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(false)
    expect(subject.reserved?).to eq(true)
  end
end
