# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.domainregistry.ie/ie/case_token_application_pending.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.domainregistry.ie", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.domainregistry.ie/ie/case_token_application_pending.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.domainregistry.ie")
    Whois::Parser.parser_for(part)
  end

  it "matches case_token_application_pending.expected" do
    expect(subject.status).to eq(:registered)
  end
end
