# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.tr/tr/response_error_invalid_input.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.nic.tr", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.nic.tr/tr/response_error_invalid_input.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.nic.tr")
    Whois::Parser.parser_for(part)
  end

  it "matches response_error_invalid_input.expected" do
    expect(subject.status).to eq(:invalid)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(false)
  end
end
