# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.dns.pt/pt/status_inactive.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.dns.pt", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.dns.pt/pt/status_inactive.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.dns.pt")
    Whois::Parser.parser_for(part)
  end

  it "matches status_inactive.expected" do
    expect(subject.status).to eq(:inactive)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(DateTime.parse("2009-02-09 00:00:00 UTC"))
    expect { subject.updated_on }.to raise_error(Whois::AttributeNotSupported)
    expect(subject.expires_on).to be_a(Time)
    expect(subject.expires_on).to eq(DateTime.parse("2014-03-01 00:00:00 UTC"))
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(0)
  end
end
