# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.verisign-grs.com/response_unavailable.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.verisign-grs.com", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.verisign-grs.com/response_unavailable.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.verisign-grs.com")
    Whois::Parser.parser_for(part)
  end

  it "matches response_unavailable.expected" do
    expect(subject.response_unavailable?).to eq(true)
  end
end
