# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.sx/sx/property_status_premium_name.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.sx", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.sx/sx/property_status_premium_name.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.sx")
    Whois::Parser.parser_for(part)
  end

  it "matches property_status_premium_name.expected" do
    expect(subject.status).to eq(:unavailable)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(false)
  end
end
