# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.dns.pl/pl/response_throttled.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.dns.pl", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.dns.pl/pl/response_throttled.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.dns.pl")
    Whois::Parser.parser_for(part)
  end

  it "matches response_throttled.expected" do
    expect(subject.response_throttled?).to eq(true)
  end
end
