# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.cz/cz/response_with_keyset.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.nic.cz", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.nic.cz/cz/response_with_keyset.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.nic.cz")
    Whois::Parser.parser_for(part)
  end

  it "matches response_with_keyset.expected" do
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(DateTime.parse("2006-01-30 18:55:00"))
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2010-03-06 15:53:04"))
    expect(subject.expires_on).to be_a(Time)
    expect(subject.expires_on).to eq(DateTime.parse("2014-01-30"))
  end
end
