# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.uk/uk/status_suspended.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.nic.uk", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.nic.uk/uk/status_suspended.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.nic.uk")
    Whois::Parser.parser_for(part)
  end

  it "matches status_suspended.expected" do
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(DateTime.parse("2008-08-30"))
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2012-02-09"))
    expect(subject.expires_on).to be_a(Time)
    expect(subject.expires_on).to eq(DateTime.parse("2010-08-30"))
    expect(subject.registrar).to be_a(Whois::Parser::Registrar)
    expect(subject.registrar.id).to eq("KEY-SYSTEMS-DE")
    expect(subject.registrar.name).to eq("Key-Systems GmbH")
    expect(subject.registrar.name).to eq("Key-Systems GmbH")
    expect(subject.registrar.url).to eq("http://www.Key-Systems.net")
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers).to eq([])
  end
end
