# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.uk/uk/status_invalid.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.nic.uk", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.nic.uk/uk/status_invalid.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.nic.uk")
    Whois::Parser.parser_for(part)
  end

  it "matches status_invalid.expected" do
    expect(subject.status).to eq(:invalid)
    expect(subject.valid?).to eq(false)
    expect(subject.invalid?).to eq(true)
  end
end
