# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.sk-nic.sk/sk/property_status_dom_exp.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.sk-nic.sk", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.sk-nic.sk/sk/property_status_dom_exp.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.sk-nic.sk")
    Whois::Parser.parser_for(part)
  end

  it "matches property_status_dom_exp.expected" do
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
  end
end
