# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.denic.de/de/status_failed.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.denic.de", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.denic.de/de/status_failed.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.denic.de")
    Whois::Parser.parser_for(part)
  end

  it "matches status_failed.expected" do
    expect(subject.status).to eq(:registered)
    expect(subject.registered?).to eq(true)
    expect(subject.available?).to eq(false)
  end
end
