# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.fi/fi/status_reserved.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.fi", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.fi/fi/status_reserved.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.fi")
    Whois::Parser.parser_for(part)
  end

  it "matches status_reserved.expected" do
    expect(subject.disclaimer).to eq("Copyright (c) Finnish Transport and Communications Agency Traficom")
    expect(subject.domain).to eq(nil)
    expect { subject.domain_id }.to raise_error(Whois::AttributeNotSupported)
    expect(subject.status).to eq(:reserved)
    expect(subject.available?).to eq(false)
    expect(subject.reserved?).to eq(true)
    expect(subject.created_on).to eq(nil)
    expect(subject.updated_on).to eq(nil)
    expect(subject.expires_on).to eq(nil)
    expect(subject.registrar).to eq(nil)
    expect { subject.registrant_contacts }.to raise_error(Whois::AttributeNotSupported)
    expect(subject.admin_contacts).to be_a(Array)
    expect(subject.admin_contacts).to eq([])
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts).to eq([])
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers).to eq([])
  end
end
