# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.domain-registry.nl/nl/property_status_inactive.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.domain-registry.nl", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.domain-registry.nl/nl/property_status_inactive.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.domain-registry.nl")
    Whois::Parser.parser_for(part)
  end

  it "matches property_status_inactive.expected" do
    expect(subject.status).to eq(:inactive)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
  end
end
