# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.tucows.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.tucows.com", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.tucows.com/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.tucows.com")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered.expected" do
    expect(subject.domain).to eq("tucows.com")
    expect(subject.domain_id).to eq("")
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(DateTime.parse("1995-09-07 04:00:00"))
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2013-08-07 23:52:35"))
    expect(subject.expires_on).to be_a(Time)
    expect(subject.expires_on).to eq(DateTime.parse("2014-09-06 04:00:00"))
    expect(subject.registrar).to be_a(Whois::Parser::Registrar)
    expect(subject.registrar.id).to eq("69")
    expect(subject.registrar.name).to eq("TUCOWS, INC.")
    expect(subject.registrar.url).to eq("http://tucowsdomains.com")
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts.size).to eq(1)
    expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
    expect(subject.registrant_contacts[0].name).to eq("DNS Administrator")
    expect(subject.registrant_contacts[0].organization).to eq("Tucows.com Co")
    expect(subject.registrant_contacts[0].address).to eq("96 Mowat Avenue")
    expect(subject.registrant_contacts[0].city).to eq("Toronto")
    expect(subject.registrant_contacts[0].zip).to eq("M6K3M1")
    expect(subject.registrant_contacts[0].state).to eq("Ontario")
    expect(subject.registrant_contacts[0].country_code).to eq("CA")
    expect(subject.registrant_contacts[0].phone).to eq("+1.4165350123 ext: 0000")
    expect(subject.registrant_contacts[0].fax).to eq("")
    expect(subject.registrant_contacts[0].email).to eq("dnsadmin@tucows.com")
    expect(subject.admin_contacts).to be_a(Array)
    expect(subject.admin_contacts.size).to eq(1)
    expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
    expect(subject.admin_contacts[0].name).to eq("DNS Administrator")
    expect(subject.admin_contacts[0].organization).to eq("Tucows ( Delaware ) Inc.")
    expect(subject.admin_contacts[0].address).to eq("96 Mowat Avenue")
    expect(subject.admin_contacts[0].city).to eq("Toronto")
    expect(subject.admin_contacts[0].zip).to eq("M6K3M1")
    expect(subject.admin_contacts[0].state).to eq("Ontario")
    expect(subject.admin_contacts[0].country_code).to eq("CA")
    expect(subject.admin_contacts[0].phone).to eq("+1.4165350123 ext: 0000")
    expect(subject.admin_contacts[0].fax).to eq("")
    expect(subject.admin_contacts[0].email).to eq("dnsadmin@tucows.com")
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts.size).to eq(1)
    expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
    expect(subject.technical_contacts[0].name).to eq("DNS Administrator")
    expect(subject.technical_contacts[0].organization).to eq("Tucows ( Delaware ) Inc.")
    expect(subject.technical_contacts[0].address).to eq("96 Mowat Avenue")
    expect(subject.technical_contacts[0].city).to eq("Toronto")
    expect(subject.technical_contacts[0].zip).to eq("M6K3M1")
    expect(subject.technical_contacts[0].state).to eq("Ontario")
    expect(subject.technical_contacts[0].country_code).to eq("CA")
    expect(subject.technical_contacts[0].phone).to eq("+1.4165350123 ext: 0000")
    expect(subject.technical_contacts[0].fax).to eq("")
    expect(subject.technical_contacts[0].email).to eq("dnsadmin@tucows.com")
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(3)
    expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[0].name).to eq("ns3.tucows.com")
    expect(subject.nameservers[0].ipv4).to eq(nil)
    expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[1].name).to eq("ns1.tucows.com")
    expect(subject.nameservers[1].ipv4).to eq(nil)
    expect(subject.nameservers[2]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[2].name).to eq("ns2.tucows.com")
    expect(subject.nameservers[2].ipv4).to eq(nil)
  end
end
