# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.norid.no/no/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.norid.no", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.norid.no/no/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.norid.no")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered.expected" do
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(DateTime.parse("2001-02-26"))
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2015-01-27"))
    expect { subject.expires_on }.to raise_error(Whois::AttributeNotSupported)
  end
end
