# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.pairnic.com/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.pairnic.com", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.pairnic.com/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.pairnic.com")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered.expected" do
    expect(subject.domain).to eq("pairnic.com")
    expect(subject.domain_id).to eq("2806983_DOMAIN_COM-VRSN")
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(DateTime.parse("1998-12-19T05:00:00.0000Z"))
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2012-09-04T13:55:30.0000Z"))
    expect(subject.expires_on).to be_a(Time)
    expect(subject.expires_on).to eq(DateTime.parse("2017-12-18T19:00:-0500Z"))
    expect(subject.registrar).to be_a(Whois::Parser::Registrar)
    expect(subject.registrar.id).to eq("99")
    expect(subject.registrar.name).to eq("pairNIC INC")
    expect(subject.registrar.url).to eq("https://www.pairnic.com")
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts.size).to eq(1)
    expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
    expect(subject.registrant_contacts[0].id).to eq("753531")
    expect(subject.registrant_contacts[0].name).to eq("Domain Administrator")
    expect(subject.registrant_contacts[0].organization).to eq("pair Networks, Inc.")
    expect(subject.registrant_contacts[0].address).to eq("2403 Sidney Street Suite 210")
    expect(subject.registrant_contacts[0].city).to eq("Pittsburgh")
    expect(subject.registrant_contacts[0].zip).to eq("15203")
    expect(subject.registrant_contacts[0].state).to eq("PA")
    expect(subject.registrant_contacts[0].country_code).to eq("US")
    expect(subject.registrant_contacts[0].phone).to eq(nil)
    expect(subject.registrant_contacts[0].fax).to eq(nil)
    expect(subject.registrant_contacts[0].email).to eq(nil)
    expect(subject.admin_contacts).to be_a(Array)
    expect(subject.admin_contacts.size).to eq(1)
    expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
    expect(subject.admin_contacts[0].id).to eq("753250")
    expect(subject.admin_contacts[0].name).to eq("Domain Administrator")
    expect(subject.admin_contacts[0].organization).to eq("pair Networks, Inc.")
    expect(subject.admin_contacts[0].address).to eq("2403 Sidney Street Suite 210")
    expect(subject.admin_contacts[0].city).to eq("Pittsburgh")
    expect(subject.admin_contacts[0].zip).to eq("15203")
    expect(subject.admin_contacts[0].state).to eq("PA")
    expect(subject.admin_contacts[0].country_code).to eq("US")
    expect(subject.admin_contacts[0].phone).to eq("+1.4123817247")
    expect(subject.admin_contacts[0].fax).to eq("+1.4123819997")
    expect(subject.admin_contacts[0].email).to eq("domain@pair.com")
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts.size).to eq(1)
    expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
    expect(subject.technical_contacts[0].id).to eq("753250")
    expect(subject.technical_contacts[0].name).to eq("Domain Administrator")
    expect(subject.technical_contacts[0].organization).to eq("pair Networks, Inc.")
    expect(subject.technical_contacts[0].address).to eq("2403 Sidney Street Suite 210")
    expect(subject.technical_contacts[0].city).to eq("Pittsburgh")
    expect(subject.technical_contacts[0].zip).to eq("15203")
    expect(subject.technical_contacts[0].state).to eq("PA")
    expect(subject.technical_contacts[0].country_code).to eq("US")
    expect(subject.technical_contacts[0].phone).to eq("+1.4123817247")
    expect(subject.technical_contacts[0].fax).to eq("+1.4123819997")
    expect(subject.technical_contacts[0].email).to eq("domain@pair.com")
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(2)
    expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[0].name).to eq("ns0.ns0.com")
    expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[1].name).to eq("ns00.ns0.com")
  end
end
