# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.dns.be/be/status_invalid.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.dns.be", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.dns.be/be/status_invalid.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.dns.be")
    Whois::Parser.parser_for(part)
  end

  it "matches status_invalid.expected" do
    expect(subject.domain).to eq("www.kimdemolenaer.be")
    expect(subject.status).to eq(:invalid)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(false)
    expect(subject.created_on).to eq(nil)
    expect { subject.updated_on }.to raise_error(Whois::AttributeNotSupported)
    expect { subject.expires_on }.to raise_error(Whois::AttributeNotSupported)
    expect(subject.registrar).to eq(nil)
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers).to eq([])
    expect(subject.response_throttled?).to eq(false)
    expect(subject.invalid?).to eq(true)
  end
end
