# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.enom.com/status_registered_with_blank_updated_date.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.enom.com", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.enom.com/status_registered_with_blank_updated_date.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.enom.com")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered_with_blank_updated_date.expected" do
    expect(subject.updated_on).to eq(nil)
  end
end
