# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.me/me/property_updated_on_is_blank.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.nic.me", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.nic.me/me/property_updated_on_is_blank.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.nic.me")
    Whois::Parser.parser_for(part)
  end

  it "matches property_updated_on_is_blank.expected" do
    expect(subject.updated_on).to be_nil
  end
end
