# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/tvwhois.verisign-grs.com/tv/property_nameserver_no_nameserver.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "tvwhois.verisign-grs.com", :aggregate_failures do

  subject do
    file = fixture("responses", "tvwhois.verisign-grs.com/tv/property_nameserver_no_nameserver.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "tvwhois.verisign-grs.com")
    Whois::Parser.parser_for(part)
  end

  it "matches property_nameserver_no_nameserver.expected" do
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers).to eq([])
  end
end
