# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.srs.net.nz/nz/status_invalid.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.srs.net.nz", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.srs.net.nz/nz/status_invalid.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.srs.net.nz")
    Whois::Parser.parser_for(part)
  end

  it "matches status_invalid.expected" do
    expect(subject.status).to eq(:invalid)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(false)
    expect(subject.created_on).to eq(nil)
    expect(subject.updated_on).to eq(nil)
    expect(subject.expires_on).to eq(nil)
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers).to eq([])
    expect(subject.valid?).to eq(false)
    expect(subject.invalid?).to eq(true)
    expect(subject.response_throttled?).to eq(false)
  end
end
