# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.cat/cat/property_status_multiple.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.cat", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.cat/cat/property_status_multiple.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.cat")
    Whois::Parser.parser_for(part)
  end

  it "matches property_status_multiple.expected" do
    expect(subject.status).to eq(["clientTransferProhibited", "clientDeleteProhibited"])
  end
end
